#!/usr/bin/env python3
"""
Chalice Terraform Configuration Patch

This script patches the chalice.tf.json file generated by AWS Chalice to fix
compatibility issues with our multi-environment Terraform setup.

WHY THIS PATCH IS NEEDED:
1. Chalice generates Terraform configs that conflict with our custom main.tf variables
2. The generated API Gateway deployment/stage resources don't align with current definitions
   and our environment-specific deployment strategy
3. Chalice includes 'output' and 'terraform' blocks that interfere with our
   centralized Terraform configuration
4. Chalice DynamoDB stream/lambda event source mapping does not support filtering at this time

WHAT THIS PATCH DOES:
- Removes conflicting 'output' and 'terraform' top-level blocks
- Removes Chalice's lambda event source mapping for DynamoDB streams
- Replaces Chalice's API Gateway deployment with environment-aware configuration
- Adds lifecycle management to prevent deployment conflicts
- Ensures stage names match our ${var.environment} pattern

This patch must run after 'chalice package' and before 'terraform apply' to
ensure successful multi-environment deployments.
"""

import json
from pathlib import Path


def patch_chalice_terraform():
    """
    Patch the chalice.tf.json file for compatibility with our Terraform setup.
    """
    # Get the chalice.tf.json path relative to this script
    script_dir = Path(__file__).parent
    chalice_tf_path = script_dir.parent / "chalice.tf.json"

    if not chalice_tf_path.exists():
        raise FileNotFoundError(
            f"chalice.tf.json not found at {chalice_tf_path}. "
            "Run 'chalice package --pkg-format terraform' first."
        )

    # Load the generated Terraform configuration
    with open(chalice_tf_path, "r") as f:
        terraform_config = json.load(f)

    # Remove top-level blocks that conflict with our main.tf
    conflicting_blocks = ["output", "terraform"]
    for block in conflicting_blocks:
        if block in terraform_config:
            del terraform_config[block]
            print(f"Removed conflicting '{block}' block")

    # Get the resource section (create if missing)
    resources = terraform_config.setdefault("resource", {})
    locals_block = terraform_config.get("locals", {})
    swagger = locals_block.get("chalice_api_swagger")
    if isinstance(swagger, str):
        locals_block["chalice_api_swagger"] = swagger.replace(
            "${var.frontend_app_url},${var.frontend_dev_app_url}",
            "${var.frontend_app_url}",
        )

    lambda_functions = resources.get("aws_lambda_function", {})
    stripe_environment = {
        "BILLING_EVENTS_TABLE_NAME": "${aws_dynamodb_table.billing_events.name}",
        "CATEGORIZATION_CACHE_TABLE_NAME": "${aws_dynamodb_table.categorization_cache.name}",
        "STRIPE_CANCEL_URL": "${var.stripe_cancel_url}",
        "STRIPE_PRICE_ID_MONTHLY": "${var.stripe_price_id_monthly}",
        "STRIPE_SECRET_KEY": "${var.stripe_secret_key}",
        "STRIPE_SUCCESS_URL": "${var.stripe_success_url}",
        "STRIPE_WEBHOOK_SECRET": "${var.stripe_webhook_secret}",
    }
    for function_config in lambda_functions.values():
        variables = function_config.setdefault("environment", {}).setdefault(
            "variables", {}
        )
        variables.pop("CLOUDFRONT_DOMAIN_NAME", None)
        variables.update(stripe_environment)

    # Remove Chalice's deprecated API Gateway resources
    gateway_resources = ["aws_api_gateway_deployment", "aws_api_gateway_stage"]
    for resource_type in gateway_resources:
        if resource_type in resources:
            del resources[resource_type]
            print(f"Removed Chalice's deprecated '{resource_type}' resource")

    # Remove to use the filtered version in databases.tf instead
    event_source_mappings = ["aws_lambda_event_source_mapping"]
    for resource_type in event_source_mappings:
        if resource_type in resources:
            del resources[resource_type]
            print(f"Removed Chalice's default '{resource_type}' resource")

    # Add environment-aware API Gateway configuration
    api_gateway_deployment = {
        "rest_api": {
            "rest_api_id": "${aws_api_gateway_rest_api.rest_api.id}",
            "lifecycle": {"create_before_destroy": True},
        }
    }

    api_gateway_stage = {
        "rest_api": {
            "deployment_id": "${aws_api_gateway_deployment.rest_api.id}",
            "rest_api_id": "${aws_api_gateway_rest_api.rest_api.id}",
            "stage_name": "${var.environment}",
        }
    }

    # Insert corrected resource blocks
    resources["aws_api_gateway_deployment"] = api_gateway_deployment
    resources["aws_api_gateway_stage"] = api_gateway_stage

    # Save the patched configuration
    with open(chalice_tf_path, "w") as f:
        json.dump(terraform_config, f, indent=2)

    print(f"Successfully patched {chalice_tf_path}")
    print("Configuration is now compatible with multi-environment deployment")


if __name__ == "__main__":
    try:
        patch_chalice_terraform()
    except Exception as e:
        print(f"Error patching Chalice Terraform config: {e}")
        exit(1)
